- name: Logstash | Add Logstash user
  ansible.builtin.user:
    name: "logstash"
    shell: "/bin/false"
    system: true
    create_home: false

- name: Logstash | Make dirs for Logstash      
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: logstash
    group: logstash
  loop:
  - /opt/logstash
  - /var/log/logstash

- name: Logstash | Download and unarchive logstash
  ansible.builtin.unarchive:
    src: "https://artifacts.opensearch.org/logstash/logstash-oss-with-opensearch-output-plugin-8.9.0-linux-x64.tar.gz"
    dest: "/opt/logstash"
    remote_src: true
    extra_opts:
    - "--strip-components=1"
    owner: logstash
    group: logstash

- name: Logstash | Make dir for custom configs
  ansible.builtin.file:
    path: "/opt/logstash/config/conf.d"
    state: directory
    owner: logstash
    group: logstash

- name: Logstash | Configure systemd unit
  ansible.builtin.copy:
    src: "files/logstash.service"
    dest: "/etc/systemd/system/logstash.service"
    mode: "0644"

- name: Logstash | Configure Logstash
  ansible.builtin.copy:
    src: files/logstash.yml
    dest: /opt/logstash/config/logstash.yml
    owner: logstash
    group: logstash
  notify: restart logstash

- name: Logstash | Configure main pipeline
  ansible.builtin.copy:
    src: files/pipelines.yml
    dest: /opt/logstash/config/pipelines.yml
    owner: logstash
    group: logstash
  notify: restart logstash

- name: Logstash | Configure custom pipeline
  ansible.builtin.template:
    src: "templates/logstash.conf.j2"
    dest: "/opt/logstash/config/conf.d/custom.conf"
    owner: logstash
    group: logstash
  notify: restart logstash

- name: Logstash | Check if Logstash is running
  ansible.builtin.systemd:
    name: "logstash"
    state: started
    daemon_reload: true

